title: FlagMotori
logo: /assets/img/logo.png
description: FlagMotori Iranian CTF Team
show_downloads: true
google_analytics:
remote_theme: 
exclude: ['_site', 'node_modules', 'script', 'LICENSE', 'README.md']
