title: FlagMotori
logo: /assets/img/logo.png
description: FlagMotori Iranian CTF Team
show_downloads: true
google_analytics:
remote_theme:
plugins:
  - jekyll-seo-tag
exclude: ['_site', 'py-scripts', 'LICENSE', 'README.md', 'tools', 'vendor']
